version: "3.8"
services:
  logicflareclient:
    container_name: logicflareclient
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - logicflareclient_v:/logicflareclient_v
    networks:
      - logicflareNetwork
    ports:
      - "3000:3000"  # Certifique-se de expor a porta correta

  proxy:
    container_name: proxy
    build:
      context: ./
      dockerfile: dockerfile.proxy
    ports:
      - "80:80"
    networks:
      - logicflareNetwork
    depends_on:
      - logicflareclient

volumes:
  logicflareclient_v:

networks:
  logicflareNetwork:
    external: true