# Etapa 2: Servir os arquivos estáticos com NGINX
FROM nginx:alpine

# Copia os arquivos estáticos da etapa anterior para o diretório padrão do NGINX
COPY --from=builder /app/dist /usr/share/nginx/html

# Expõe a porta padrão do NGINX
EXPOSE 80

# Inicia o NGINX em modo foreground
CMD ["nginx", "-g", "daemon off;"]