version: "3.8"
services:
  barbeariagomesclient:
    container_name: barbeariagomesclient
    build:
      context: ./ # Certifique-se de que o contexto aponta para o diretório correto
      dockerfile: dockerfile
    networks:
      - barbeariaNetwork

  barbeariagomes_proxy:
    container_name: barbeariagomes_proxy
    build:
      context: ./ # Certifique-se de que o contexto aponta para o diretório correto
      dockerfile: dockerfile.proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - barbeariaNetwork
    depends_on:
      - barbeariagomesclient

networks:
  barbeariaNetwork:
    external: true
